from django import forms


class CountryForm(forms.Form):
    FILTER_CHOICES = (
        ('all',"Select Country Name"),
        ('afghanistan', 'Afghanistan'),
        ('albania', 'Albania'),
        ('algeria', 'Algeria'),
        ('andorra', 'Andorra'),
        ('angola', 'Angola'),
        ('anguilla', 'Anguilla'),
        ('antiguaandbarbuda', 'Antigua and Barbuda'),
        ('argentina', 'Argentina'),
        ('armenia', 'Armenia'),
        ('aruba', 'Aruba'),
        ('australia', 'Australia'),
        ('austria', 'Austria'),
        ('azerbaijan', 'Azerbaijan'),
        ('bahamas', 'Bahamas'),
        ('bahrain', 'Bahrain'),
        ('bangladesh', 'Bangladesh'),
        ('barbados', 'Barbados'),
        ('belarus', 'Belarus'),
        ('belgium', 'Belgium'),
        ('belize', 'Belize'),
        ('benin', 'Benin'),
        ('bermuda', 'Bermuda'),
        ('bhutan', 'Bhutan'),
        ('bolivia', 'Bolivia'),
        ('bosniaandherzegovina', 'Bosnia and Herzegovina'),
        ('botswana', 'Botswana'),
        ('brazil', 'Brazil'),
        ('britishvirginislands', 'British Virgin Islands'),
        ('brunei', 'Brunei'),
        ('bulgaria', 'Bulgaria'),
        ('burkinafaso', 'Burkina Faso'),
        ('burundi', 'Burundi'),
        ('caboverde', 'Cabo Verde'),
        ('cambodia', 'Cambodia'),
        ('cameroon', 'Cameroon'),
        ('canada', 'Canada'),
        ('car', 'CAR'),
        ('caribbeannetherlands', 'Caribbean Netherlands'),
        ('caymanislands', 'Cayman Islands'),
        ('chad', 'Chad'),
        ('channelislands', 'Channel Islands'),
        ('chile', 'Chile'),
        ('china', 'China'),
        ('colombia', 'Colombia'),
        ('comoros', 'Comoros'),
        ('congo', 'Congo'),
        ('costarica', 'Costa Rica'),
        ('croatia', 'Croatia'),
        ('cuba', 'Cuba'),
        ('curaçao', 'Curaçao'),
        ('cyprus', 'Cyprus'),
        ('czechia', 'Czechia'),
        ('denmark', 'Denmark'),
        ('diamondprincess', 'Diamond Princess'),
        ('djibouti', 'Djibouti'),
        ('dominica', 'Dominica'),
        ('dominicanrepublic', 'Dominican Republic'),
        ('drc', 'DRC'),
        ('ecuador', 'Ecuador'),
        ('egypt', 'Egypt'),
        ('elsalvador', 'El Salvador'),
        ('equatorialguinea', 'Equatorial Guinea'),
        ('eritrea', 'Eritrea'),
        ('estonia', 'Estonia'),
        ('eswatini', 'Eswatini'),
        ('ethiopia', 'Ethiopia'),
        ('faeroeislands', 'Faeroe Islands'),
        ('falklandislands', 'Falkland Islands'),
        ('fiji', 'Fiji'),
        ('finland', 'Finland'),
        ('france', 'France'),
        ('frenchguiana', 'French Guiana'),
        ('frenchpolynesia', 'French Polynesia'),
        ('gabon', 'Gabon'),
        ('gambia', 'Gambia'),
        ('georgia', 'Georgia'),
        ('germany', 'Germany'),
        ('ghana', 'Ghana'),
        ('gibraltar', 'Gibraltar'),
        ('greece', 'Greece'),
        ('greenland', 'Greenland'),
        ('grenada', 'Grenada'),
        ('guadeloupe', 'Guadeloupe'),
        ('guatemala', 'Guatemala'),
        ('guinea', 'Guinea'),
        ('guinea-bissau', 'Guinea-Bissau'),
        ('guyana', 'Guyana'),
        ('haiti', 'Haiti'),
        ('honduras', 'Honduras'),
        ('hongkong', 'Hong Kong'),
        ('hungary', 'Hungary'),
        ('iceland', 'Iceland'),
        ('india', 'India'),
        ('indonesia', 'Indonesia'),
        ('iran', 'Iran'),
        ('iraq', 'Iraq'),
        ('ireland', 'Ireland'),
        ('isleofman', 'Isle of Man'),
        ('israel', 'Israel'),
        ('italy', 'Italy'),
        ('ivorycoast', 'Ivory Coast'),
        ('jamaica', 'Jamaica'),
        ('japan', 'Japan'),
        ('jordan', 'Jordan'),
        ('kazakhstan', 'Kazakhstan'),
        ('kenya', 'Kenya'),
        ('kuwait', 'Kuwait'),
        ('kyrgyzstan', 'Kyrgyzstan'),
        ('laos', 'Laos'),
        ('latvia', 'Latvia'),
        ('lebanon', 'Lebanon'),
        ('liberia', 'Liberia'),
        ('libya', 'Libya'),
        ('liechtenstein', 'Liechtenstein'),
        ('lithuania', 'Lithuania'),
        ('luxembourg', 'Luxembourg'),
        ('macao', 'Macao'),
        ('madagascar', 'Madagascar'),
        ('malawi', 'Malawi'),
        ('malaysia', 'Malaysia'),
        ('maldives', 'Maldives'),
        ('mali', 'Mali'),
        ('malta', 'Malta'),
        ('martinique', 'Martinique'),
        ('mauritania', 'Mauritania'),
        ('mauritius', 'Mauritius'),
        ('mayotte', 'Mayotte'),
        ('mexico', 'Mexico'),
        ('moldova', 'Moldova'),
        ('monaco', 'Monaco'),
        ('mongolia', 'Mongolia'),
        ('montenegro', 'Montenegro'),
        ('montserrat', 'Montserrat'),
        ('morocco', 'Morocco'),
        ('mozambique', 'Mozambique'),
        ('mszaandam', 'MS Zaandam'),
        ('myanmar', 'Myanmar'),
        ('namibia', 'Namibia'),
        ('nepal', 'Nepal'),
        ('netherlands', 'Netherlands'),
        ('newcaledonia', 'New Caledonia'),
        ('newzealand', 'New Zealand'),
        ('nicaragua', 'Nicaragua'),
        ('niger', 'Niger'),
        ('nigeria', 'Nigeria'),
        ('northmacedonia', 'North Macedonia'),
        ('norway', 'Norway'),
        ('oman', 'Oman'),
        ('pakistan', 'Pakistan'),
        ('palestine', 'Palestine'),
        ('panama', 'Panama'),
        ('papuanewguinea', 'Papua New Guinea'),
        ('paraguay', 'Paraguay'),
        ('peru', 'Peru'),
        ('philippines', 'Philippines'),
        ('poland', 'Poland'),
        ('portugal', 'Portugal'),
        ('qatar', 'Qatar'),
        ('romania', 'Romania'),
        ('russia', 'Russia'),
        ('rwanda', 'Rwanda'),
        ('réunion', 'Réunion'),
        ('s.korea', 'S. Korea'),
        ('saintkittsandnevis', 'Saint Kitts and Nevis'),
        ('saintlucia', 'Saint Lucia'),
        ('saintmartin', 'Saint Martin'),
        ('saintpierremiquelon', 'Saint Pierre Miquelon'),
        ('sanmarino', 'San Marino'),
        ('saotomeandprincipe', 'Sao Tome and Principe'),
        ('saudiarabia', 'Saudi Arabia'),
        ('senegal', 'Senegal'),
        ('serbia', 'Serbia'),
        ('seychelles', 'Seychelles'),
        ('sierraleone', 'Sierra Leone'),
        ('singapore', 'Singapore'),
        ('sintmaarten', 'Sint Maarten'),
        ('slovakia', 'Slovakia'),
        ('slovenia', 'Slovenia'),
        ('somalia', 'Somalia'),
        ('southafrica', 'South Africa'),
        ('southsudan', 'South Sudan'),
        ('spain', 'Spain'),
        ('srilanka', 'Sri Lanka'),
        ('st.barth', 'St. Barth'),
        ('st.vincentgrenadines', 'St. Vincent Grenadines'),
        ('sudan', 'Sudan'),
        ('suriname', 'Suriname'),
        ('sweden', 'Sweden'),
        ('switzerland', 'Switzerland'),
        ('syria', 'Syria'),
        ('taiwan', 'Taiwan'),
        ('tajikistan', 'Tajikistan'),
        ('tanzania', 'Tanzania'),
        ('thailand', 'Thailand'),
        ('timor-leste', 'Timor-Leste'),
        ('togo', 'Togo'),
        ('trinidadandtobago', 'Trinidad and Tobago'),
        ('tunisia', 'Tunisia'),
        ('turkey', 'Turkey'),
        ('turksandcaicos', 'Turks and Caicos'),
        ('uae', 'UAE'),
        ('uganda', 'Uganda'),
        ('uk', 'UK'),
        ('ukraine', 'Ukraine'),
        ('uruguay', 'Uruguay'),
        ('usa', 'USA'),
        ('uzbekistan', 'Uzbekistan'),
        ('vaticancity', 'Vatican City'),
        ('venezuela', 'Venezuela'),
        ('vietnam', 'Vietnam'),
        ('westernsahara', 'Western Sahara'),
        ('yemen', 'Yemen'),
        ('zambia', 'Zambia'),
        ('zimbabwe', 'Zimbabwe'),
    )

    deaths_by_country = forms.ChoiceField(choices = FILTER_CHOICES,widget=forms.Select(attrs={'class':'selectpicker c text-muted', 'onchange': 'submit();'}))